'use client';

import { useState } from 'react';
import { FileText, Download, FileDown, FileCode } from 'lucide-react';
import { useToast } from './ErrorToast';

interface IncidentData {
  incident_id: string;
  title: string;
  severity: string;
  duration_minutes: number;
  services_affected: string[];
  root_cause: {
    primary: string;
    secondary?: string;
  };
  mitigation_steps: string[];
  lessons_learned?: string[];
}

interface AnalysisData {
  executive_summary: string;
  root_cause: {
    primary_cause: string;
    confidence: number;
    evidence: string[];
    contributing_factors?: string[];
  };
  impact: {
    users_affected: string;
    estimated_cost: string;
    services_impacted: string[];
  };
  recommended_actions: Array<{
    priority: string;
    action: string;
    estimated_time: string;
    risk_level: string;
  }>;
  timeline_summary: string;
}

interface RCADocumentGeneratorProps {
  incident: IncidentData;
  analysis: AnalysisData | null;
}

export default function RCADocumentGenerator({ incident, analysis }: RCADocumentGeneratorProps) {
  const [isGenerating, setIsGenerating] = useState(false);
  const { showToast } = useToast();

  const generateMarkdown = (): string => {
    const date = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });

    let doc = `# Root Cause Analysis Report\n\n`;
    doc += `**Incident ID:** ${incident.incident_id}\n`;
    doc += `**Title:** ${incident.title}\n`;
    doc += `**Severity:** ${incident.severity}\n`;
    doc += `**Date:** ${date}\n`;
    doc += `**Duration:** ${Math.floor(incident.duration_minutes / 60)}h ${incident.duration_minutes % 60}m\n\n`;
    doc += `---\n\n`;

    if (analysis) {
      doc += `## Executive Summary\n\n`;
      doc += `${analysis.executive_summary}\n\n`;

      doc += `## Root Cause Analysis\n\n`;
      doc += `### Primary Cause\n\n`;
      doc += `${analysis.root_cause.primary_cause}\n\n`;
      doc += `**Confidence Level:** ${Math.round(analysis.root_cause.confidence * 100)}%\n\n`;

      if (analysis.root_cause.evidence && analysis.root_cause.evidence.length > 0) {
        doc += `### Evidence\n\n`;
        analysis.root_cause.evidence.forEach((evidence, i) => {
          doc += `${i + 1}. ${evidence}\n`;
        });
        doc += `\n`;
      }

      if (analysis.root_cause.contributing_factors && analysis.root_cause.contributing_factors.length > 0) {
        doc += `### Contributing Factors\n\n`;
        analysis.root_cause.contributing_factors.forEach((factor, i) => {
          doc += `${i + 1}. ${factor}\n`;
        });
        doc += `\n`;
      }

      doc += `## Impact Assessment\n\n`;
      doc += `- **Users Affected:** ${analysis.impact.users_affected}\n`;
      doc += `- **Estimated Cost:** ${analysis.impact.estimated_cost}\n`;
      doc += `- **Services Impacted:** ${analysis.impact.services_impacted.join(', ')}\n\n`;

      doc += `## Recommended Actions\n\n`;
      analysis.recommended_actions.forEach((action, i) => {
        doc += `### ${i + 1}. ${action.priority} Priority\n\n`;
        doc += `**Action:** ${action.action}\n\n`;
        doc += `**Estimated Time:** ${action.estimated_time}\n`;
        doc += `**Risk Level:** ${action.risk_level}\n\n`;
      });

      doc += `## Timeline Summary\n\n`;
      doc += `${analysis.timeline_summary}\n\n`;
    } else {
      doc += `## Root Cause\n\n`;
      doc += `**Primary:** ${incident.root_cause.primary}\n\n`;
      if (incident.root_cause.secondary) {
        doc += `**Secondary:** ${incident.root_cause.secondary}\n\n`;
      }
    }

    doc += `## Mitigation Steps\n\n`;
    incident.mitigation_steps.forEach((step, i) => {
      doc += `${i + 1}. ${step}\n`;
    });
    doc += `\n`;

    doc += `## Affected Services\n\n`;
    incident.services_affected.forEach((service) => {
      doc += `- ${service}\n`;
    });
    doc += `\n`;

    if (incident.lessons_learned && incident.lessons_learned.length > 0) {
      doc += `## Lessons Learned\n\n`;
      incident.lessons_learned.forEach((lesson, i) => {
        doc += `${i + 1}. ${lesson}\n`;
      });
      doc += `\n`;
    }

    doc += `---\n\n`;
    doc += `*Generated by WardenXT AI-Powered Incident Commander*\n`;
    doc += `*Powered by Gemini 3*\n`;

    return doc;
  };

  const generateHTML = (): string => {
    const markdown = generateMarkdown();
    // Simple markdown to HTML conversion
    let html = `<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <title>RCA Report - ${incident.incident_id}</title>
  <style>
    body { font-family: -apple-system, BlinkMacSystemFont, 'Segoe UI', sans-serif; max-width: 800px; margin: 40px auto; padding: 20px; line-height: 1.6; }
    h1 { color: #1e293b; border-bottom: 3px solid #3b82f6; padding-bottom: 10px; }
    h2 { color: #334155; margin-top: 30px; }
    h3 { color: #475569; }
    code { background: #f1f5f9; padding: 2px 6px; border-radius: 3px; }
    pre { background: #f1f5f9; padding: 15px; border-radius: 5px; overflow-x: auto; }
    ul, ol { margin-left: 20px; }
    hr { border: none; border-top: 2px solid #e2e8f0; margin: 30px 0; }
  </style>
</head>
<body>
${markdown
  .replace(/^# (.*$)/gim, '<h1>$1</h1>')
  .replace(/^## (.*$)/gim, '<h2>$1</h2>')
  .replace(/^### (.*$)/gim, '<h3>$1</h3>')
  .replace(/\*\*(.*?)\*\*/gim, '<strong>$1</strong>')
  .replace(/\*(.*?)\*/gim, '<em>$1</em>')
  .replace(/^\- (.*$)/gim, '<li>$1</li>')
  .replace(/^(\d+)\. (.*$)/gim, '<li>$2</li>')
  .replace(/\n\n/gim, '</p><p>')
  .replace(/^<p>/gim, '')
  .replace(/<\/p>$/gim, '')}
</body>
</html>`;
    return html;
  };

  const downloadMarkdown = () => {
    try {
      setIsGenerating(true);
      const markdown = generateMarkdown();
      const blob = new Blob([markdown], { type: 'text/markdown' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `RCA-${incident.incident_id}.md`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      showToast('Markdown document downloaded', 'success');
    } catch (error) {
      showToast('Failed to generate document', 'error');
    } finally {
      setIsGenerating(false);
    }
  };

  const downloadHTML = () => {
    try {
      setIsGenerating(true);
      const html = generateHTML();
      const blob = new Blob([html], { type: 'text/html' });
      const url = URL.createObjectURL(blob);
      const a = document.createElement('a');
      a.href = url;
      a.download = `RCA-${incident.incident_id}.html`;
      document.body.appendChild(a);
      a.click();
      document.body.removeChild(a);
      URL.revokeObjectURL(url);
      showToast('HTML document downloaded', 'success');
    } catch (error) {
      showToast('Failed to generate document', 'error');
    } finally {
      setIsGenerating(false);
    }
  };

  const printPDF = () => {
    try {
      setIsGenerating(true);
      const html = generateHTML();
      const printWindow = window.open('', '_blank');
      if (printWindow) {
        printWindow.document.write(html);
        printWindow.document.close();
        printWindow.onload = () => {
          printWindow.print();
        };
        showToast('Opening print dialog for PDF', 'info');
      }
    } catch (error) {
      showToast('Failed to generate PDF', 'error');
    } finally {
      setIsGenerating(false);
    }
  };

  return (
    <div className="bg-slate-900/50 border border-slate-800 rounded-lg p-6">
      <div className="flex items-center gap-3 mb-4">
        <FileText className="h-6 w-6 text-blue-400" />
        <h2 className="text-xl font-bold text-white">RCA Document Generator</h2>
      </div>

      <p className="text-slate-400 text-sm mb-6">
        Generate a comprehensive Root Cause Analysis document for this incident. The document includes
        all analysis details, evidence, and recommendations.
      </p>

      <div className="flex flex-wrap gap-3">
        <button
          onClick={downloadMarkdown}
          disabled={isGenerating}
          className="flex items-center gap-2 px-4 py-2 bg-slate-800 hover:bg-slate-700 text-white rounded-lg transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
        >
          <FileCode className="h-4 w-4" />
          Download Markdown
        </button>

        <button
          onClick={downloadHTML}
          disabled={isGenerating}
          className="flex items-center gap-2 px-4 py-2 bg-slate-800 hover:bg-slate-700 text-white rounded-lg transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
        >
          <FileDown className="h-4 w-4" />
          Download HTML
        </button>

        <button
          onClick={printPDF}
          disabled={isGenerating}
          className="flex items-center gap-2 px-4 py-2 bg-blue-600 hover:bg-blue-700 text-white rounded-lg transition-colors disabled:opacity-50 disabled:cursor-not-allowed"
        >
          <Download className="h-4 w-4" />
          Print as PDF
        </button>
      </div>

      {isGenerating && (
        <div className="mt-4 text-sm text-slate-400 flex items-center gap-2">
          <div className="animate-spin rounded-full h-4 w-4 border-2 border-blue-500 border-t-transparent"></div>
          Generating document...
        </div>
      )}
    </div>
  );
}
