'use client';

import { Runbook } from '@/lib/api';

export function exportRunbookAsMarkdown(runbook: Runbook): void {
  const markdown = generateRunbookMarkdown(runbook);

  // Create blob and download
  const blob = new Blob([markdown], { type: 'text/markdown' });
  const url = URL.createObjectURL(blob);
  const a = document.createElement('a');
  a.href = url;
  a.download = `runbook-${runbook.incident_id}.md`;
  document.body.appendChild(a);
  a.click();
  document.body.removeChild(a);
  URL.revokeObjectURL(url);
}

function generateRunbookMarkdown(runbook: Runbook): string {
  const { incident_id, incident_type, severity, steps, estimated_total_time, warnings, prerequisites } = runbook;

  let md = `# Runbook: ${incident_id}\n\n`;
  md += `**Generated:** ${new Date(runbook.generated_at).toLocaleString()}\n\n`;
  md += `**Incident Type:** ${incident_type}\n\n`;
  md += `**Severity:** ${severity}\n\n`;
  md += `**Estimated Time:** ${estimated_total_time}\n\n`;

  // Warnings
  if (warnings.length > 0) {
    md += `## ⚠️ Warnings\n\n`;
    warnings.forEach(warning => {
      md += `- ${warning}\n`;
    });
    md += `\n`;
  }

  // Prerequisites
  if (prerequisites.length > 0) {
    md += `## 📋 Prerequisites\n\n`;
    prerequisites.forEach(prereq => {
      md += `- ${prereq}\n`;
    });
    md += `\n`;
  }

  // Table of Contents
  md += `## 📖 Table of Contents\n\n`;
  steps.forEach(step => {
    md += `${step.step_number}. [${step.title}](#step-${step.step_number})\n`;
  });
  md += `\n---\n\n`;

  // Steps
  steps.forEach(step => {
    md += `## Step ${step.step_number}: ${step.title} {#step-${step.step_number}}\n\n`;
    md += `**Category:** ${step.category}\n\n`;
    md += `**Estimated Duration:** ${step.estimated_duration}\n\n`;

    if (step.prerequisite_steps.length > 0) {
      md += `**Prerequisites:** Complete step${step.prerequisite_steps.length > 1 ? 's' : ''} ${step.prerequisite_steps.join(', ')} first\n\n`;
    }

    step.commands.forEach((command, idx) => {
      md += `### Command ${idx + 1}\n\n`;
      md += `**Description:** ${command.description}\n\n`;
      md += `**Risk Level:** ${command.risk_level.toUpperCase()}\n\n`;
      md += `**Requires Approval:** ${command.requires_approval ? 'Yes' : 'No'}\n\n`;
      md += `**Timeout:** ${command.timeout_seconds}s\n\n`;

      md += `\`\`\`bash\n${command.command}\n\`\`\`\n\n`;

      if (command.expected_output) {
        md += `**Expected Output:**\n\n`;
        md += `\`\`\`\n${command.expected_output}\n\`\`\`\n\n`;
      }

      md += `- [ ] Executed\n- [ ] Verified\n\n`;
    });

    md += `---\n\n`;
  });

  // Footer
  md += `---\n\n`;
  md += `*Generated by WardenXT - AI-Powered Incident Commander*\n\n`;
  md += `*Powered by Google Gemini 3 Flash*\n`;

  return md;
}

// Component for export button
interface RunbookExportButtonProps {
  runbook: Runbook;
  className?: string;
}

export default function RunbookExportButton({ runbook, className }: RunbookExportButtonProps) {
  return (
    <button
      onClick={() => exportRunbookAsMarkdown(runbook)}
      className={className}
    >
      Export as Markdown
    </button>
  );
}
